Добавил 2 таску
selfoma/NSU-Android-Course pull request #2
Opened 2024-09-28 17:43 UTC by selfoma

Не очень доволен, как написаны xml-ки, но, вроде, ничего так получилось.

2024-09-29 12:52 UTC, Romchirik requested changes

2024-09-29 12:52 UTC, Romchirik commented on Layout/app/src/main/java/nsu/fomin/layout/recycler/PlayerRecyclerAdapter.kt
> +            else -> {
Тут нужно сделать такую же ветку как с `AdvertisementViewHolder`, а ветку else оставить пустую (`else -> {}`), и тогда не придется делать каст на 71ой строке

2024-09-29 12:52 UTC, Romchirik commented on Layout/app/src/main/res/layout/advertisement_item.xml
> +<?xml version="1.0" encoding="utf-8"?>
По верстке нужно максимально попасть в макет, в целом расположение элементов верное, но с размерами картинок и отступами беда . Картинкам нужно прибить размеры гвоздями как в макете (48x48dp и 96x56dp), Отступы тоже нужно зафиксить

2024-09-30 11:54 UTC, selfoma commented on Layout/app/src/main/java/nsu/fomin/layout/recycler/PlayerRecyclerAdapter.kt
> +            else -> {
Я изначально и сделал, что исключение кидается в else, но потом подумал, что типа такого же не может быть, поэтому переделал на это...

2024-09-30 11:55 UTC, selfoma commented on Layout/app/src/main/res/layout/advertisement_item.xml
> +<?xml version="1.0" encoding="utf-8"?>
Вроде, переделал. Вроде, захардкодил все отступы. Но выглядит все равно так себе :)

2024-10-10 16:55 UTC, Romchirik approved these changes

2024-10-16 08:18 UTC, merged