Сделал 3 таску
selfoma/NSU-Android-Course pull request #3
Opened 2024-10-07 06:07 UTC by selfoma

Дизайн тупо из 80-х, но красота в строгости

2024-10-09 08:54 UTC, selfoma commented
Сделал, чтоб можно было и в горизонталке смотреть. Но пришлось обернуть в LinearLayout потому что если обернуть просто в ScrollView, то это тип ub. И у меня вот просто не запускается эта активити. В принципе, можешь посмотреть и прошлый дизайн, там получше.

2024-10-10 12:31 UTC, Romchirik requested changes

2024-10-10 12:31 UTC, Romchirik commented on Converter/app/src/main/java/nsu/fomin/converter/activities/BootActivity.kt
> +            intent.putExtra("valuteMap", valuteMap)
Константу надо вынести в переменную и прокидывать ее через переменную, таким образом, если поменяешь что-то, не придется по всему приложению бегать и искать вхождения строчки

2024-10-10 12:31 UTC, Romchirik commented on Converter/app/src/main/java/nsu/fomin/converter/activities/BootActivity.kt
> +        CoroutineScope(Dispatchers.IO + SupervisorJob()).launch {
А зачем тут супервизор жоба?

2024-10-10 12:31 UTC, Romchirik commented on Converter/app/src/main/java/nsu/fomin/converter/activities/BootActivity.kt
> +        CoroutineScope(Dispatchers.IO + SupervisorJob()).launch {
Вообще, надо бы заюзать вот эту либу "androidx.lifecycle:lifecycle-runtime-ktx:2.8.3" (если я не ошибаюсь) и глянуть вот эту статейку https://developer.android.com/topic/libraries/architecture/coroutines, после прочтения нужно привязать получение валют к лайфсаклу, чтобы приложение в фоне не ходило в сеть

2024-10-10 12:31 UTC, Romchirik commented on Converter/app/src/main/java/nsu/fomin/converter/valute/SerializableValute.kt
> +    val list: JsonObject? = null,
Ни на что не намекаю, но если пихнуть мапу вместо JsonObject, можно спарсить значение намного проще 
<img width="427" alt="image" src="https://github.com/user-attachments/assets/5fa372f2-9533-4bff-8c7f-617eed05619f">

2024-10-11 05:13 UTC, selfoma commented on Converter/app/src/main/java/nsu/fomin/converter/activities/BootActivity.kt
> +            intent.putExtra("valuteMap", valuteMap)
Я так обычно и делаю, стараюсь выносить машические штуки куда-то вне. Но в таких маленьких приложухах иногда впадлу.

2024-10-11 05:15 UTC, selfoma commented on Converter/app/src/main/java/nsu/fomin/converter/activities/BootActivity.kt
> +        CoroutineScope(Dispatchers.IO + SupervisorJob()).launch {
Тут не нужен жоба, но обычно супервизор применяется в UI-приложениях, поэтому решил написать :). Типа все равно дочерних корутин нет, так что что жоба, что супервизор...

2024-10-11 05:37 UTC, selfoma commented on Converter/app/src/main/java/nsu/fomin/converter/valute/SerializableValute.kt
> +    val list: JsonObject? = null,
Реально....Акшали я пробовал, но, видимо, где-то наложал и там exception вылетал. А вот щас переделал - реально работает

2024-10-11 12:43 UTC, Romchirik requested changes

2024-10-11 12:43 UTC, Romchirik commented on Converter/app/src/main/java/nsu/fomin/converter/activities/BootActivity.kt
> +        lifecycleScope.launch {
Относительно предыдущего варианта ничего не поменялось)) Ты все еще разрешаешь запускаться задаче в фоне. Глянь что такое repeatOnLifecycle, этой штуки тут не хватает

2024-10-12 09:07 UTC, selfoma commented
Ну да, я понял, что просто добавление жизненного цикла не исправляет ситуацию, так как все равно при паузе активити она будет продолжать работать в фоном режиме, поэтому когда пауза/удаление нужно канселить корутины. Поэтому ставим repeat... и теперь она создается и запускается, когда активити onStart, onResume и канселится, когда уходит в background или уничтожается.  
![image](https://github.com/user-attachments/assets/90835a51-eab7-472c-bd99-0276072de8c2)

2024-10-14 03:49 UTC, Romchirik approved these changes

2024-10-16 08:18 UTC, merged